### ISSUE TITLE
Mention that crate is unix-only in Readme

### ISSUE THREAD

**Issue by Shadlock0133** [joshtriplett/highlight-stderr#1]
After reading that this crate uses posix sockets through `io-mux` I know it's unix-only, but mentioning it in readme would be helpful for others.

**Comment by joshtriplett** [comment]
Will do, thank you for the reminder.

**Comment by joshtriplett** [comment]
Fixed in https://github.com/joshtriplett/highlight-stderr/commit/d76a2f4c79c7d0c9e83b7f14ce0d05bb321d97ff . I don't want to spin a new release just for this note, but it'll appear in the next release, and on GitHub.
