### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by baodrate** [joshtriplett/highlight-stderr#4]
FYI, in case it was not omitted on purpose, there is currently no license provided with this repo

**Comment by joshtriplett** [comment]
It's `MIT OR Apache-2.0` like many other Rust crates: https://github.com/joshtriplett/highlight-stderr/blob/master/Cargo.toml#L10C1-L10C30

I don't think there's value in including the full license texts for those well-known licenses.

**Comment by baodrate** [comment]
Ah I missed that, sorry. But I think there is a lot of value in having the actual text of the license. For one, I'm not sure if just having the line in the Cargo.toml actually gives the user a license. Technically, it's just configuration for cargo. If you're not using cargo/crates.io, e.g. you're vendoring and using bazel, it is at best a signal that the copyright owner *intended* to license the code under those licenses.

The more practical reason is that it's convention to include the license as a `LICENSE` file at the top of the project. It's both convenient and unambiguous for users and for tooling. On github, for example, this repo nor io-mux show up [if you specify `license:MIT` in the search](https://github.com/search?q=io-mux+license%3AMIT&ref=opensearch&type=repositories). Also note that every other rust crate (that I can think of) includes a `LICENSE` file.

Anyways, it's your project and this confirmation is good enough for my purposes. 

edit: Also note that conditions under which you're allowed to use the code under both licenses. MIT:

> Permission is hereby granted..., subject to the following conditions:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

And Apache-2.0:

> You may reproduce and distribute copies of the Work or Derivative Works thereof in any medium, with or without modifications, and in Source or Object form, provided that You meet the following conditions:

> You must give any other recipients of the Work or Derivative Works a copy of this License; and

I'm not sure it's possible to actually abide by the licenses without including the actual licenses.
